# mern stack

services:
  client:
    build: ./client
    ports:
      - "80:3000"
    volumes:
      - ./client/src:/usr/src/app
      - /usr/src/app/node_modules
      
  server:
    build: ./server
    ports:
      - "3000:3000"
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db